config/routes.rb
Rails.application.routes.draw do
  resources :rubists
  devise_for :users
  get 'welcome/index'
  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rubist.rb
class Rubist < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/rubists_controller.rb
class RubistsController < ApplicationController
  before_action :set_rubist, only: [:show, :edit, :update, :destroy]

  # GET /rubists
  # GET /rubists.json
  def index
    @rubists = Rubist.all
  end

  # GET /rubists/1
  # GET /rubists/1.json
  def show
  end

  # GET /rubists/new
  def new
    @rubist = Rubist.new
  end

  # GET /rubists/1/edit
  def edit
  end

  # POST /rubists
  # POST /rubists.json
  def create
    @rubist = Rubist.new(rubist_params)

    respond_to do |format|
      if @rubist.save
        format.html { redirect_to @rubist, notice: 'Rubist was successfully created.' }
        format.json { render :show, status: :created, location: @rubist }
      else
        format.html { render :new }
        format.json { render json: @rubist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubists/1
  # PATCH/PUT /rubists/1.json
  def update
    respond_to do |format|
      if @rubist.update(rubist_params)
        format.html { redirect_to @rubist, notice: 'Rubist was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubist }
      else
        format.html { render :edit }
        format.json { render json: @rubist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubists/1
  # DELETE /rubists/1.json
  def destroy
    @rubist.destroy
    respond_to do |format|
      format.html { redirect_to rubists_url, notice: 'Rubist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubist
      @rubist = Rubist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubist_params
      params.require(:rubist).permit(:name, :dob, :age, :email, :experience)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rubists_helper.rb
module RubistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rubyonrails" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Rubyonrails</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
            <li>
            	<% if user_signed_in? %>
            		<%= link_to "SignOut", destroy_user_session_path, :method => "delete" %>
            		<li><%= link_to "Hi #{current_user.email}","/" %></li>
            	<% else %>
            		<%= link_to "Signin", new_user_session_path %>
            	<% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/rubists/_form.html.erb
<%= form_for @rubist, :html => { :class => "form-horizontal rubist" } do |f| %>

  <% if @rubist.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@rubist.errors.count, "error") %> prohibited this rubist from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @rubist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :dob, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :dob, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dob) %>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :experience, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :experience, :class => 'form-control' %>
    </div>
    <%=f.error_span(:experience) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rubists_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/rubists/edit.html.erb
<%- model_class = Rubist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rubists/index.html.erb
<%- model_class = Rubist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:experience) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rubists.each do |rubist| %>
      <tr>
        <td><%= link_to rubist.id, rubist_path(rubist) %></td>
        <td><%= rubist.name %></td>
        <td><%= rubist.dob %></td>
        <td><%= rubist.age %></td>
        <td><%= rubist.email %></td>
        <td><%= rubist.experience %></td>
        <td><%=l rubist.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      rubist_path(rubist), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rubist_path(rubist), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rubist_path(rubist),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rubist_path,
            :class => 'btn btn-primary' %>

app/views/rubists/new.html.erb
<%- model_class = Rubist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rubists/show.html.erb
<%- model_class = Rubist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @rubist.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @rubist.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @rubist.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @rubist.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:experience) %>:</strong></dt>
  <dd><%= @rubist.experience %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              rubists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rubist_path(@rubist), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rubist_path(@rubist),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<%= link_to "Rubyist", rubists_path %>